# Generated by Django 6.1.1 on 2026-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_create_permission_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Allegderly', max_length=200, verbose_name='Company name')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State / province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='ZIP / postal code')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID / registration no.')),
                ('invoice_footer', models.CharField(blank=True, default='Thank you for your business.', help_text='Printed at the bottom of every invoice.', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'company profile',
            },
        ),
    ]
