# Generated by Django 6.1.1 on 2026-10-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='has_damage',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='has_return',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='credit_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='refund_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20, null=True),
        ),
    ]
