# Generated by Django 6.1.1 on 2026-10-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_creditnote_return_record_invoice_tax_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.CharField(blank=True, help_text='Optional free-text reason', max_length=255, null=True),
        ),
    ]
