# Generated by Django 6.1.1 on 2026-10-03 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_reported', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice_line', models.ForeignKey(blank=True, help_text='Optional, for reference only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_records', to='invoices.invoiceline')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_reports', to='inventory.item')),
            ],
        ),
    ]
