# Generated by Django 6.1.1 on 2026-10-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
