# Generated by Django 6.1.1 on 2026-10-07 19:07

from django.db import migrations, models


def split_names_and_addresses(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    for customer in Customer.objects.all():
        parts = (customer.name or '').split()
        customer.first_name = parts[0] if parts else ''
        customer.last_name = parts[-1] if len(parts) > 1 else ''
        customer.middle_name = ' '.join(parts[1:-1])
        lines = [ln.strip() for ln in (customer.address or '').splitlines() if ln.strip()]
        if lines:
            customer.billing_line1 = lines[0][:200]
            customer.billing_line2 = ', '.join(lines[1:])[:200]
        customer.save(update_fields=[
            'first_name', 'middle_name', 'last_name', 'billing_line1', 'billing_line2',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_line1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_line2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Apt, suite, unit'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='ZIP / postal code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State / province'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='print_name',
            field=models.CharField(blank=True, help_text='Leave blank to use the customer name.', max_length=200, verbose_name='Name to print on invoice'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_line1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_line2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Apt, suite, unit'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='ZIP / postal code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_same_as_billing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State / province'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(editable=False, max_length=300),
        ),
        migrations.RunPython(split_names_and_addresses, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
