# Generated by Django 6.1.1 on 2026-10-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('raw_materials', 'Raw materials'), ('packaging', 'Packaging'), ('equipment', 'Equipment & supplies'), ('services', 'Services'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=20)),
                ('tax_id', models.CharField(blank=True, help_text="Vendor's tax registration number, if any.", max_length=50, null=True, verbose_name='Tax ID / GSTIN')),
                ('payment_terms', models.CharField(choices=[('due_on_receipt', 'Due on receipt'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60')], default='net_30', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
